//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onvif.Actionengine
{

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl", ConfigurationName="ActionEnginePort")]
public interface ActionEnginePort
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/actionengine/wsdl/GetSupportedActions", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="SupportedActions")]
    SupportedActions GetSupportedActions();
    
    // CODEGEN: Parameter 'Action' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/actionengine/wsdl/GetActions", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="Action")]
    GetActionsResponse GetActions(GetActionsRequest request);
    
    // CODEGEN: Parameter 'Action' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/actionengine/wsdl/CreateActions", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    CreateActionsResponse CreateActions(CreateActionsRequest request);
    
    // CODEGEN: Parameter 'Token' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/actionengine/wsdl/DeleteActions", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    DeleteActionsResponse DeleteActions(DeleteActionsRequest request);
    
    // CODEGEN: Parameter 'Action' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/actionengine/wsdl/ModifyActions", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    ModifyActionsResponse ModifyActions(ModifyActionsRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/actionengine/wsdl/GetServiceCapabilities", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="Capabilities")]
    ActionEngineCapabilities GetServiceCapabilities();
    
    // CODEGEN: Parameter 'ActionTrigger' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/actionengine/wsdl/GetActionTriggers", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="ActionTrigger")]
    GetActionTriggersResponse GetActionTriggers(GetActionTriggersRequest request);
    
    // CODEGEN: Parameter 'ActionTrigger' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/actionengine/wsdl/CreateActionTriggers", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    CreateActionTriggersResponse CreateActionTriggers(CreateActionTriggersRequest request);
    
    // CODEGEN: Parameter 'Token' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/actionengine/wsdl/DeleteActionTriggers", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    DeleteActionTriggersResponse DeleteActionTriggers(DeleteActionTriggersRequest request);
    
    // CODEGEN: Parameter 'ActionTrigger' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/actionengine/wsdl/ModifyActionTriggers", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    ModifyActionTriggersResponse ModifyActionTriggers(ModifyActionTriggersRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl")]
public partial class SupportedActions
{
    
    private string[] actionContentSchemaLocationField;
    
    private ActionConfigDescription[] actionDescriptionField;
    
    private SupportedActionsExtension extensionField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ActionContentSchemaLocation", DataType="anyURI", Order=0)]
    public string[] ActionContentSchemaLocation
    {
        get
        {
            return this.actionContentSchemaLocationField;
        }
        set
        {
            this.actionContentSchemaLocationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ActionDescription", Order=1)]
    public ActionConfigDescription[] ActionDescription
    {
        get
        {
            return this.actionDescriptionField;
        }
        set
        {
            this.actionDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public SupportedActionsExtension Extension
    {
        get
        {
            return this.extensionField;
        }
        set
        {
            this.extensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl")]
public partial class ActionConfigDescription
{
    
    private ItemListDescription parameterDescriptionField;
    
    private System.Xml.XmlQualifiedName nameField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public ItemListDescription ParameterDescription
    {
        get
        {
            return this.parameterDescriptionField;
        }
        set
        {
            this.parameterDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.Xml.XmlQualifiedName Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class ItemListDescription
{
    
    private ItemListDescriptionSimpleItemDescription[] simpleItemDescriptionField;
    
    private ItemListDescriptionElementItemDescription[] elementItemDescriptionField;
    
    private ItemListDescriptionExtension extensionField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SimpleItemDescription", Order=0)]
    public ItemListDescriptionSimpleItemDescription[] SimpleItemDescription
    {
        get
        {
            return this.simpleItemDescriptionField;
        }
        set
        {
            this.simpleItemDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ElementItemDescription", Order=1)]
    public ItemListDescriptionElementItemDescription[] ElementItemDescription
    {
        get
        {
            return this.elementItemDescriptionField;
        }
        set
        {
            this.elementItemDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public ItemListDescriptionExtension Extension
    {
        get
        {
            return this.extensionField;
        }
        set
        {
            this.extensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.onvif.org/ver10/schema")]
public partial class ItemListDescriptionSimpleItemDescription
{
    
    private string nameField;
    
    private System.Xml.XmlQualifiedName typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.Xml.XmlQualifiedName Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl")]
public partial class ActionTriggerConfigurationExtension
{
    
    private System.Xml.XmlElement[] anyField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wsn/b-2")]
public partial class QueryExpressionType
{
    
    private System.Xml.XmlNode[] anyField;
    
    private string dialectField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    public System.Xml.XmlNode[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Dialect
    {
        get
        {
            return this.dialectField;
        }
        set
        {
            this.dialectField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wsn/b-2")]
public partial class TopicExpressionType
{
    
    private System.Xml.XmlNode[] anyField;
    
    private string dialectField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    public System.Xml.XmlNode[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Dialect
    {
        get
        {
            return this.dialectField;
        }
        set
        {
            this.dialectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl")]
public partial class ActionTriggerConfiguration
{
    
    private TopicExpressionType topicExpressionField;
    
    private QueryExpressionType contentExpressionField;
    
    private string[] actionTokenField;
    
    private ActionTriggerConfigurationExtension extensionField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public TopicExpressionType TopicExpression
    {
        get
        {
            return this.topicExpressionField;
        }
        set
        {
            this.topicExpressionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public QueryExpressionType ContentExpression
    {
        get
        {
            return this.contentExpressionField;
        }
        set
        {
            this.contentExpressionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ActionToken", Order=2)]
    public string[] ActionToken
    {
        get
        {
            return this.actionTokenField;
        }
        set
        {
            this.actionTokenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public ActionTriggerConfigurationExtension Extension
    {
        get
        {
            return this.extensionField;
        }
        set
        {
            this.extensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl")]
public partial class ActionTrigger
{
    
    private ActionTriggerConfiguration configurationField;
    
    private System.Xml.XmlElement[] anyField;
    
    private string tokenField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public ActionTriggerConfiguration Configuration
    {
        get
        {
            return this.configurationField;
        }
        set
        {
            this.configurationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Token
    {
        get
        {
            return this.tokenField;
        }
        set
        {
            this.tokenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl")]
public partial class ActionEngineCapabilitiesExtension
{
    
    private System.Xml.XmlElement[] anyField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl")]
public partial class ActionTypeLimits
{
    
    private System.Xml.XmlElement[] anyField;
    
    private System.Xml.XmlQualifiedName typeField;
    
    private string maximumField;
    
    private string inUseField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    public ActionTypeLimits()
    {
        this.inUseField = "0";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.Xml.XmlQualifiedName Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string Maximum
    {
        get
        {
            return this.maximumField;
        }
        set
        {
            this.maximumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    [System.ComponentModel.DefaultValueAttribute("0")]
    public string InUse
    {
        get
        {
            return this.inUseField;
        }
        set
        {
            this.inUseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl")]
public partial class ActionEngineCapabilities
{
    
    private ActionTypeLimits[] actionCapabilitiesField;
    
    private ActionEngineCapabilitiesExtension extensionField;
    
    private string maximumTriggersField;
    
    private string maximumActionsField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ActionCapabilities", Order=0)]
    public ActionTypeLimits[] ActionCapabilities
    {
        get
        {
            return this.actionCapabilitiesField;
        }
        set
        {
            this.actionCapabilitiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public ActionEngineCapabilitiesExtension Extension
    {
        get
        {
            return this.extensionField;
        }
        set
        {
            this.extensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string MaximumTriggers
    {
        get
        {
            return this.maximumTriggersField;
        }
        set
        {
            this.maximumTriggersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string MaximumActions
    {
        get
        {
            return this.maximumActionsField;
        }
        set
        {
            this.maximumActionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class ItemListExtension
{
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class ItemList
{
    
    private ItemListSimpleItem[] simpleItemField;
    
    private ItemListElementItem[] elementItemField;
    
    private ItemListExtension extensionField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SimpleItem", Order=0)]
    public ItemListSimpleItem[] SimpleItem
    {
        get
        {
            return this.simpleItemField;
        }
        set
        {
            this.simpleItemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ElementItem", Order=1)]
    public ItemListElementItem[] ElementItem
    {
        get
        {
            return this.elementItemField;
        }
        set
        {
            this.elementItemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public ItemListExtension Extension
    {
        get
        {
            return this.extensionField;
        }
        set
        {
            this.extensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.onvif.org/ver10/schema")]
public partial class ItemListSimpleItem
{
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.onvif.org/ver10/schema")]
public partial class ItemListElementItem
{
    
    private System.Xml.XmlElement anyField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    public System.Xml.XmlElement Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl")]
public partial class ActionConfiguration
{
    
    private ItemList parametersField;
    
    private System.Xml.XmlElement[] anyField;
    
    private string nameField;
    
    private System.Xml.XmlQualifiedName typeField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public ItemList Parameters
    {
        get
        {
            return this.parametersField;
        }
        set
        {
            this.parametersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.Xml.XmlQualifiedName Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl")]
public partial class Action
{
    
    private ActionConfiguration configurationField;
    
    private System.Xml.XmlElement[] anyField;
    
    private string tokenField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public ActionConfiguration Configuration
    {
        get
        {
            return this.configurationField;
        }
        set
        {
            this.configurationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Token
    {
        get
        {
            return this.tokenField;
        }
        set
        {
            this.tokenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl")]
public partial class SupportedActionsExtension
{
    
    private System.Xml.XmlElement[] anyField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class ItemListDescriptionExtension
{
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.onvif.org/ver10/schema")]
public partial class ItemListDescriptionElementItemDescription
{
    
    private string nameField;
    
    private System.Xml.XmlQualifiedName typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.Xml.XmlQualifiedName Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetActions", WrapperNamespace="http://www.onvif.org/ver10/actionengine/wsdl", IsWrapped=true)]
public partial class GetActionsRequest
{
    
    public GetActionsRequest()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetActionsResponse", WrapperNamespace="http://www.onvif.org/ver10/actionengine/wsdl", IsWrapped=true)]
public partial class GetActionsResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("Action")]
    public Action[] Action;
    
    public GetActionsResponse()
    {
    }
    
    public GetActionsResponse(Action[] Action)
    {
        this.Action = Action;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="CreateActions", WrapperNamespace="http://www.onvif.org/ver10/actionengine/wsdl", IsWrapped=true)]
public partial class CreateActionsRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("Action")]
    public ActionConfiguration[] Action;
    
    public CreateActionsRequest()
    {
    }
    
    public CreateActionsRequest(ActionConfiguration[] Action)
    {
        this.Action = Action;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="CreateActionsResponse", WrapperNamespace="http://www.onvif.org/ver10/actionengine/wsdl", IsWrapped=true)]
public partial class CreateActionsResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("Action")]
    public Action[] Action;
    
    public CreateActionsResponse()
    {
    }
    
    public CreateActionsResponse(Action[] Action)
    {
        this.Action = Action;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="DeleteActions", WrapperNamespace="http://www.onvif.org/ver10/actionengine/wsdl", IsWrapped=true)]
public partial class DeleteActionsRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("Token")]
    public string[] Token;
    
    public DeleteActionsRequest()
    {
    }
    
    public DeleteActionsRequest(string[] Token)
    {
        this.Token = Token;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="DeleteActionsResponse", WrapperNamespace="http://www.onvif.org/ver10/actionengine/wsdl", IsWrapped=true)]
public partial class DeleteActionsResponse
{
    
    public DeleteActionsResponse()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="ModifyActions", WrapperNamespace="http://www.onvif.org/ver10/actionengine/wsdl", IsWrapped=true)]
public partial class ModifyActionsRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("Action")]
    public Action[] Action;
    
    public ModifyActionsRequest()
    {
    }
    
    public ModifyActionsRequest(Action[] Action)
    {
        this.Action = Action;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="ModifyActionsResponse", WrapperNamespace="http://www.onvif.org/ver10/actionengine/wsdl", IsWrapped=true)]
public partial class ModifyActionsResponse
{
    
    public ModifyActionsResponse()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetActionTriggers", WrapperNamespace="http://www.onvif.org/ver10/actionengine/wsdl", IsWrapped=true)]
public partial class GetActionTriggersRequest
{
    
    public GetActionTriggersRequest()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetActionTriggersResponse", WrapperNamespace="http://www.onvif.org/ver10/actionengine/wsdl", IsWrapped=true)]
public partial class GetActionTriggersResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("ActionTrigger")]
    public ActionTrigger[] ActionTrigger;
    
    public GetActionTriggersResponse()
    {
    }
    
    public GetActionTriggersResponse(ActionTrigger[] ActionTrigger)
    {
        this.ActionTrigger = ActionTrigger;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="CreateActionTriggers", WrapperNamespace="http://www.onvif.org/ver10/actionengine/wsdl", IsWrapped=true)]
public partial class CreateActionTriggersRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("ActionTrigger")]
    public ActionTriggerConfiguration[] ActionTrigger;
    
    public CreateActionTriggersRequest()
    {
    }
    
    public CreateActionTriggersRequest(ActionTriggerConfiguration[] ActionTrigger)
    {
        this.ActionTrigger = ActionTrigger;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="CreateActionTriggersResponse", WrapperNamespace="http://www.onvif.org/ver10/actionengine/wsdl", IsWrapped=true)]
public partial class CreateActionTriggersResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("ActionTrigger")]
    public ActionTrigger[] ActionTrigger;
    
    public CreateActionTriggersResponse()
    {
    }
    
    public CreateActionTriggersResponse(ActionTrigger[] ActionTrigger)
    {
        this.ActionTrigger = ActionTrigger;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="DeleteActionTriggers", WrapperNamespace="http://www.onvif.org/ver10/actionengine/wsdl", IsWrapped=true)]
public partial class DeleteActionTriggersRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("Token")]
    public string[] Token;
    
    public DeleteActionTriggersRequest()
    {
    }
    
    public DeleteActionTriggersRequest(string[] Token)
    {
        this.Token = Token;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="DeleteActionTriggersResponse", WrapperNamespace="http://www.onvif.org/ver10/actionengine/wsdl", IsWrapped=true)]
public partial class DeleteActionTriggersResponse
{
    
    public DeleteActionTriggersResponse()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="ModifyActionTriggers", WrapperNamespace="http://www.onvif.org/ver10/actionengine/wsdl", IsWrapped=true)]
public partial class ModifyActionTriggersRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/actionengine/wsdl", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("ActionTrigger")]
    public ActionTrigger[] ActionTrigger;
    
    public ModifyActionTriggersRequest()
    {
    }
    
    public ModifyActionTriggersRequest(ActionTrigger[] ActionTrigger)
    {
        this.ActionTrigger = ActionTrigger;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="ModifyActionTriggersResponse", WrapperNamespace="http://www.onvif.org/ver10/actionengine/wsdl", IsWrapped=true)]
public partial class ModifyActionTriggersResponse
{
    
    public ModifyActionTriggersResponse()
    {
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ActionEnginePortChannel : ActionEnginePort, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ActionEnginePortClient : System.ServiceModel.ClientBase<ActionEnginePort>, ActionEnginePort
{
    
    public ActionEnginePortClient()
    {
    }
    
    public ActionEnginePortClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ActionEnginePortClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ActionEnginePortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ActionEnginePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public SupportedActions GetSupportedActions()
    {
        return base.Channel.GetSupportedActions();
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetActionsResponse ActionEnginePort.GetActions(GetActionsRequest request)
    {
        return base.Channel.GetActions(request);
    }
    
    public Action[] GetActions()
    {
        GetActionsRequest inValue = new GetActionsRequest();
        GetActionsResponse retVal = ((ActionEnginePort)(this)).GetActions(inValue);
        return retVal.Action;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    CreateActionsResponse ActionEnginePort.CreateActions(CreateActionsRequest request)
    {
        return base.Channel.CreateActions(request);
    }
    
    public Action[] CreateActions(ActionConfiguration[] Action)
    {
        CreateActionsRequest inValue = new CreateActionsRequest();
        inValue.Action = Action;
        CreateActionsResponse retVal = ((ActionEnginePort)(this)).CreateActions(inValue);
        return retVal.Action;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    DeleteActionsResponse ActionEnginePort.DeleteActions(DeleteActionsRequest request)
    {
        return base.Channel.DeleteActions(request);
    }
    
    public void DeleteActions(string[] Token)
    {
        DeleteActionsRequest inValue = new DeleteActionsRequest();
        inValue.Token = Token;
        DeleteActionsResponse retVal = ((ActionEnginePort)(this)).DeleteActions(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ModifyActionsResponse ActionEnginePort.ModifyActions(ModifyActionsRequest request)
    {
        return base.Channel.ModifyActions(request);
    }
    
    public void ModifyActions(Action[] Action)
    {
        ModifyActionsRequest inValue = new ModifyActionsRequest();
        inValue.Action = Action;
        ModifyActionsResponse retVal = ((ActionEnginePort)(this)).ModifyActions(inValue);
    }
    
    public ActionEngineCapabilities GetServiceCapabilities()
    {
        return base.Channel.GetServiceCapabilities();
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetActionTriggersResponse ActionEnginePort.GetActionTriggers(GetActionTriggersRequest request)
    {
        return base.Channel.GetActionTriggers(request);
    }
    
    public ActionTrigger[] GetActionTriggers()
    {
        GetActionTriggersRequest inValue = new GetActionTriggersRequest();
        GetActionTriggersResponse retVal = ((ActionEnginePort)(this)).GetActionTriggers(inValue);
        return retVal.ActionTrigger;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    CreateActionTriggersResponse ActionEnginePort.CreateActionTriggers(CreateActionTriggersRequest request)
    {
        return base.Channel.CreateActionTriggers(request);
    }
    
    public ActionTrigger[] CreateActionTriggers(ActionTriggerConfiguration[] ActionTrigger)
    {
        CreateActionTriggersRequest inValue = new CreateActionTriggersRequest();
        inValue.ActionTrigger = ActionTrigger;
        CreateActionTriggersResponse retVal = ((ActionEnginePort)(this)).CreateActionTriggers(inValue);
        return retVal.ActionTrigger;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    DeleteActionTriggersResponse ActionEnginePort.DeleteActionTriggers(DeleteActionTriggersRequest request)
    {
        return base.Channel.DeleteActionTriggers(request);
    }
    
    public void DeleteActionTriggers(string[] Token)
    {
        DeleteActionTriggersRequest inValue = new DeleteActionTriggersRequest();
        inValue.Token = Token;
        DeleteActionTriggersResponse retVal = ((ActionEnginePort)(this)).DeleteActionTriggers(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ModifyActionTriggersResponse ActionEnginePort.ModifyActionTriggers(ModifyActionTriggersRequest request)
    {
        return base.Channel.ModifyActionTriggers(request);
    }
    
    public void ModifyActionTriggers(ActionTrigger[] ActionTrigger)
    {
        ModifyActionTriggersRequest inValue = new ModifyActionTriggersRequest();
        inValue.ActionTrigger = ActionTrigger;
        ModifyActionTriggersResponse retVal = ((ActionEnginePort)(this)).ModifyActionTriggers(inValue);
    }
}
}