//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onvif.Analytics
{

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.onvif.org/ver20/analytics/wsdl", ConfigurationName="RuleEnginePort")]
public interface RuleEnginePort
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver20/analytics/wsdl/GetSupportedRules", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageDescription))]
    [return: System.ServiceModel.MessageParameterAttribute(Name="SupportedRules")]
    SupportedRules GetSupportedRules(string ConfigurationToken);
    
    // CODEGEN: Parameter 'Rule' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver20/analytics/wsdl/CreateRules", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageDescription))]
    CreateRulesResponse CreateRules(CreateRulesRequest request);
    
    // CODEGEN: Parameter 'RuleName' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver20/analytics/wsdl/DeleteRules", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageDescription))]
    DeleteRulesResponse DeleteRules(DeleteRulesRequest request);
    
    // CODEGEN: Parameter 'Rule' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver20/analytics/wsdl/GetRules", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageDescription))]
    [return: System.ServiceModel.MessageParameterAttribute(Name="Rule")]
    GetRulesResponse GetRules(GetRulesRequest request);
    
    // CODEGEN: Parameter 'Rule' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver20/analytics/wsdl/ModifyRules", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageDescription))]
    ModifyRulesResponse ModifyRules(ModifyRulesRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class SupportedRules
{
    
    private string[] ruleContentSchemaLocationField;
    
    private ConfigDescription[] ruleDescriptionField;
    
    private SupportedRulesExtension extensionField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RuleContentSchemaLocation", DataType="anyURI", Order=0)]
    public string[] RuleContentSchemaLocation
    {
        get
        {
            return this.ruleContentSchemaLocationField;
        }
        set
        {
            this.ruleContentSchemaLocationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RuleDescription", Order=1)]
    public ConfigDescription[] RuleDescription
    {
        get
        {
            return this.ruleDescriptionField;
        }
        set
        {
            this.ruleDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public SupportedRulesExtension Extension
    {
        get
        {
            return this.extensionField;
        }
        set
        {
            this.extensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class ConfigDescription
{
    
    private ItemListDescription parametersField;
    
    private ConfigDescriptionMessages[] messagesField;
    
    private ConfigDescriptionExtension extensionField;
    
    private System.Xml.XmlQualifiedName nameField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public ItemListDescription Parameters
    {
        get
        {
            return this.parametersField;
        }
        set
        {
            this.parametersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Messages", Order=1)]
    public ConfigDescriptionMessages[] Messages
    {
        get
        {
            return this.messagesField;
        }
        set
        {
            this.messagesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public ConfigDescriptionExtension Extension
    {
        get
        {
            return this.extensionField;
        }
        set
        {
            this.extensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.Xml.XmlQualifiedName Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class ItemListDescription
{
    
    private ItemListDescriptionSimpleItemDescription[] simpleItemDescriptionField;
    
    private ItemListDescriptionElementItemDescription[] elementItemDescriptionField;
    
    private ItemListDescriptionExtension extensionField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SimpleItemDescription", Order=0)]
    public ItemListDescriptionSimpleItemDescription[] SimpleItemDescription
    {
        get
        {
            return this.simpleItemDescriptionField;
        }
        set
        {
            this.simpleItemDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ElementItemDescription", Order=1)]
    public ItemListDescriptionElementItemDescription[] ElementItemDescription
    {
        get
        {
            return this.elementItemDescriptionField;
        }
        set
        {
            this.elementItemDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public ItemListDescriptionExtension Extension
    {
        get
        {
            return this.extensionField;
        }
        set
        {
            this.extensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.onvif.org/ver10/schema")]
public partial class ItemListDescriptionSimpleItemDescription
{
    
    private string nameField;
    
    private System.Xml.XmlQualifiedName typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.Xml.XmlQualifiedName Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class SupportedAnalyticsModulesExtension
{
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class SupportedAnalyticsModules
{
    
    private string[] analyticsModuleContentSchemaLocationField;
    
    private ConfigDescription[] analyticsModuleDescriptionField;
    
    private SupportedAnalyticsModulesExtension extensionField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AnalyticsModuleContentSchemaLocation", DataType="anyURI", Order=0)]
    public string[] AnalyticsModuleContentSchemaLocation
    {
        get
        {
            return this.analyticsModuleContentSchemaLocationField;
        }
        set
        {
            this.analyticsModuleContentSchemaLocationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AnalyticsModuleDescription", Order=1)]
    public ConfigDescription[] AnalyticsModuleDescription
    {
        get
        {
            return this.analyticsModuleDescriptionField;
        }
        set
        {
            this.analyticsModuleDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public SupportedAnalyticsModulesExtension Extension
    {
        get
        {
            return this.extensionField;
        }
        set
        {
            this.extensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver20/analytics/wsdl")]
public partial class Capabilities
{
    
    private System.Xml.XmlElement[] anyField;
    
    private bool ruleSupportField;
    
    private bool ruleSupportFieldSpecified;
    
    private bool analyticsModuleSupportField;
    
    private bool analyticsModuleSupportFieldSpecified;
    
    private bool cellBasedSceneDescriptionSupportedField;
    
    private bool cellBasedSceneDescriptionSupportedFieldSpecified;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool RuleSupport
    {
        get
        {
            return this.ruleSupportField;
        }
        set
        {
            this.ruleSupportField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RuleSupportSpecified
    {
        get
        {
            return this.ruleSupportFieldSpecified;
        }
        set
        {
            this.ruleSupportFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool AnalyticsModuleSupport
    {
        get
        {
            return this.analyticsModuleSupportField;
        }
        set
        {
            this.analyticsModuleSupportField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AnalyticsModuleSupportSpecified
    {
        get
        {
            return this.analyticsModuleSupportFieldSpecified;
        }
        set
        {
            this.analyticsModuleSupportFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool CellBasedSceneDescriptionSupported
    {
        get
        {
            return this.cellBasedSceneDescriptionSupportedField;
        }
        set
        {
            this.cellBasedSceneDescriptionSupportedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CellBasedSceneDescriptionSupportedSpecified
    {
        get
        {
            return this.cellBasedSceneDescriptionSupportedFieldSpecified;
        }
        set
        {
            this.cellBasedSceneDescriptionSupportedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class ItemListExtension
{
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class ItemList
{
    
    private ItemListSimpleItem[] simpleItemField;
    
    private ItemListElementItem[] elementItemField;
    
    private ItemListExtension extensionField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SimpleItem", Order=0)]
    public ItemListSimpleItem[] SimpleItem
    {
        get
        {
            return this.simpleItemField;
        }
        set
        {
            this.simpleItemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ElementItem", Order=1)]
    public ItemListElementItem[] ElementItem
    {
        get
        {
            return this.elementItemField;
        }
        set
        {
            this.elementItemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public ItemListExtension Extension
    {
        get
        {
            return this.extensionField;
        }
        set
        {
            this.extensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.onvif.org/ver10/schema")]
public partial class ItemListSimpleItem
{
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.onvif.org/ver10/schema")]
public partial class ItemListElementItem
{
    
    private System.Xml.XmlElement anyField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    public System.Xml.XmlElement Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class Config
{
    
    private ItemList parametersField;
    
    private string nameField;
    
    private System.Xml.XmlQualifiedName typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public ItemList Parameters
    {
        get
        {
            return this.parametersField;
        }
        set
        {
            this.parametersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.Xml.XmlQualifiedName Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class SupportedRulesExtension
{
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class ConfigDescriptionExtension
{
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class MessageDescriptionExtension
{
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class MessageDescription
{
    
    private ItemListDescription sourceField;
    
    private ItemListDescription keyField;
    
    private ItemListDescription dataField;
    
    private MessageDescriptionExtension extensionField;
    
    private bool isPropertyField;
    
    private bool isPropertyFieldSpecified;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public ItemListDescription Source
    {
        get
        {
            return this.sourceField;
        }
        set
        {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public ItemListDescription Key
    {
        get
        {
            return this.keyField;
        }
        set
        {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public ItemListDescription Data
    {
        get
        {
            return this.dataField;
        }
        set
        {
            this.dataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public MessageDescriptionExtension Extension
    {
        get
        {
            return this.extensionField;
        }
        set
        {
            this.extensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool IsProperty
    {
        get
        {
            return this.isPropertyField;
        }
        set
        {
            this.isPropertyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsPropertySpecified
    {
        get
        {
            return this.isPropertyFieldSpecified;
        }
        set
        {
            this.isPropertyFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class ItemListDescriptionExtension
{
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.onvif.org/ver10/schema")]
public partial class ItemListDescriptionElementItemDescription
{
    
    private string nameField;
    
    private System.Xml.XmlQualifiedName typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.Xml.XmlQualifiedName Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.onvif.org/ver10/schema")]
public partial class ConfigDescriptionMessages : MessageDescription
{
    
    private string parentTopicField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string ParentTopic
    {
        get
        {
            return this.parentTopicField;
        }
        set
        {
            this.parentTopicField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="CreateRules", WrapperNamespace="http://www.onvif.org/ver20/analytics/wsdl", IsWrapped=true)]
public partial class CreateRulesRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver20/analytics/wsdl", Order=0)]
    public string ConfigurationToken;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver20/analytics/wsdl", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute("Rule")]
    public Config[] Rule;
    
    public CreateRulesRequest()
    {
    }
    
    public CreateRulesRequest(string ConfigurationToken, Config[] Rule)
    {
        this.ConfigurationToken = ConfigurationToken;
        this.Rule = Rule;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="CreateRulesResponse", WrapperNamespace="http://www.onvif.org/ver20/analytics/wsdl", IsWrapped=true)]
public partial class CreateRulesResponse
{
    
    public CreateRulesResponse()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="DeleteRules", WrapperNamespace="http://www.onvif.org/ver20/analytics/wsdl", IsWrapped=true)]
public partial class DeleteRulesRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver20/analytics/wsdl", Order=0)]
    public string ConfigurationToken;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver20/analytics/wsdl", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute("RuleName")]
    public string[] RuleName;
    
    public DeleteRulesRequest()
    {
    }
    
    public DeleteRulesRequest(string ConfigurationToken, string[] RuleName)
    {
        this.ConfigurationToken = ConfigurationToken;
        this.RuleName = RuleName;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="DeleteRulesResponse", WrapperNamespace="http://www.onvif.org/ver20/analytics/wsdl", IsWrapped=true)]
public partial class DeleteRulesResponse
{
    
    public DeleteRulesResponse()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetRules", WrapperNamespace="http://www.onvif.org/ver20/analytics/wsdl", IsWrapped=true)]
public partial class GetRulesRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver20/analytics/wsdl", Order=0)]
    public string ConfigurationToken;
    
    public GetRulesRequest()
    {
    }
    
    public GetRulesRequest(string ConfigurationToken)
    {
        this.ConfigurationToken = ConfigurationToken;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetRulesResponse", WrapperNamespace="http://www.onvif.org/ver20/analytics/wsdl", IsWrapped=true)]
public partial class GetRulesResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver20/analytics/wsdl", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("Rule")]
    public Config[] Rule;
    
    public GetRulesResponse()
    {
    }
    
    public GetRulesResponse(Config[] Rule)
    {
        this.Rule = Rule;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="ModifyRules", WrapperNamespace="http://www.onvif.org/ver20/analytics/wsdl", IsWrapped=true)]
public partial class ModifyRulesRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver20/analytics/wsdl", Order=0)]
    public string ConfigurationToken;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver20/analytics/wsdl", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute("Rule")]
    public Config[] Rule;
    
    public ModifyRulesRequest()
    {
    }
    
    public ModifyRulesRequest(string ConfigurationToken, Config[] Rule)
    {
        this.ConfigurationToken = ConfigurationToken;
        this.Rule = Rule;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="ModifyRulesResponse", WrapperNamespace="http://www.onvif.org/ver20/analytics/wsdl", IsWrapped=true)]
public partial class ModifyRulesResponse
{
    
    public ModifyRulesResponse()
    {
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface RuleEnginePortChannel : RuleEnginePort, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class RuleEnginePortClient : System.ServiceModel.ClientBase<RuleEnginePort>, RuleEnginePort
{
    
    public RuleEnginePortClient()
    {
    }
    
    public RuleEnginePortClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public RuleEnginePortClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RuleEnginePortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RuleEnginePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public SupportedRules GetSupportedRules(string ConfigurationToken)
    {
        return base.Channel.GetSupportedRules(ConfigurationToken);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    CreateRulesResponse RuleEnginePort.CreateRules(CreateRulesRequest request)
    {
        return base.Channel.CreateRules(request);
    }
    
    public void CreateRules(string ConfigurationToken, Config[] Rule)
    {
        CreateRulesRequest inValue = new CreateRulesRequest();
        inValue.ConfigurationToken = ConfigurationToken;
        inValue.Rule = Rule;
        CreateRulesResponse retVal = ((RuleEnginePort)(this)).CreateRules(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    DeleteRulesResponse RuleEnginePort.DeleteRules(DeleteRulesRequest request)
    {
        return base.Channel.DeleteRules(request);
    }
    
    public void DeleteRules(string ConfigurationToken, string[] RuleName)
    {
        DeleteRulesRequest inValue = new DeleteRulesRequest();
        inValue.ConfigurationToken = ConfigurationToken;
        inValue.RuleName = RuleName;
        DeleteRulesResponse retVal = ((RuleEnginePort)(this)).DeleteRules(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetRulesResponse RuleEnginePort.GetRules(GetRulesRequest request)
    {
        return base.Channel.GetRules(request);
    }
    
    public Config[] GetRules(string ConfigurationToken)
    {
        GetRulesRequest inValue = new GetRulesRequest();
        inValue.ConfigurationToken = ConfigurationToken;
        GetRulesResponse retVal = ((RuleEnginePort)(this)).GetRules(inValue);
        return retVal.Rule;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ModifyRulesResponse RuleEnginePort.ModifyRules(ModifyRulesRequest request)
    {
        return base.Channel.ModifyRules(request);
    }
    
    public void ModifyRules(string ConfigurationToken, Config[] Rule)
    {
        ModifyRulesRequest inValue = new ModifyRulesRequest();
        inValue.ConfigurationToken = ConfigurationToken;
        inValue.Rule = Rule;
        ModifyRulesResponse retVal = ((RuleEnginePort)(this)).ModifyRules(inValue);
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.onvif.org/ver20/analytics/wsdl", ConfigurationName="AnalyticsEnginePort")]
public interface AnalyticsEnginePort
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver20/analytics/wsdl/GetServiceCapabilities", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageDescription))]
    [return: System.ServiceModel.MessageParameterAttribute(Name="Capabilities")]
    Capabilities GetServiceCapabilities();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver20/analytics/wsdl/GetSupportedAnalyticsModules", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageDescription))]
    [return: System.ServiceModel.MessageParameterAttribute(Name="SupportedAnalyticsModules")]
    SupportedAnalyticsModules GetSupportedAnalyticsModules(string ConfigurationToken);
    
    // CODEGEN: Parameter 'AnalyticsModule' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver20/analytics/wsdl/CreateAnalyticsModules", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageDescription))]
    CreateAnalyticsModulesResponse CreateAnalyticsModules(CreateAnalyticsModulesRequest request);
    
    // CODEGEN: Parameter 'AnalyticsModuleName' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver20/analytics/wsdl/DeleteAnalyticsModules", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageDescription))]
    DeleteAnalyticsModulesResponse DeleteAnalyticsModules(DeleteAnalyticsModulesRequest request);
    
    // CODEGEN: Parameter 'AnalyticsModule' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver20/analytics/wsdl/GetAnalyticsModules", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageDescription))]
    [return: System.ServiceModel.MessageParameterAttribute(Name="AnalyticsModule")]
    GetAnalyticsModulesResponse GetAnalyticsModules(GetAnalyticsModulesRequest request);
    
    // CODEGEN: Parameter 'AnalyticsModule' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver20/analytics/wsdl/ModifyAnalyticsModules", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageDescription))]
    ModifyAnalyticsModulesResponse ModifyAnalyticsModules(ModifyAnalyticsModulesRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="CreateAnalyticsModules", WrapperNamespace="http://www.onvif.org/ver20/analytics/wsdl", IsWrapped=true)]
public partial class CreateAnalyticsModulesRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver20/analytics/wsdl", Order=0)]
    public string ConfigurationToken;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver20/analytics/wsdl", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute("AnalyticsModule")]
    public Config[] AnalyticsModule;
    
    public CreateAnalyticsModulesRequest()
    {
    }
    
    public CreateAnalyticsModulesRequest(string ConfigurationToken, Config[] AnalyticsModule)
    {
        this.ConfigurationToken = ConfigurationToken;
        this.AnalyticsModule = AnalyticsModule;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="CreateAnalyticsModulesResponse", WrapperNamespace="http://www.onvif.org/ver20/analytics/wsdl", IsWrapped=true)]
public partial class CreateAnalyticsModulesResponse
{
    
    public CreateAnalyticsModulesResponse()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="DeleteAnalyticsModules", WrapperNamespace="http://www.onvif.org/ver20/analytics/wsdl", IsWrapped=true)]
public partial class DeleteAnalyticsModulesRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver20/analytics/wsdl", Order=0)]
    public string ConfigurationToken;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver20/analytics/wsdl", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute("AnalyticsModuleName")]
    public string[] AnalyticsModuleName;
    
    public DeleteAnalyticsModulesRequest()
    {
    }
    
    public DeleteAnalyticsModulesRequest(string ConfigurationToken, string[] AnalyticsModuleName)
    {
        this.ConfigurationToken = ConfigurationToken;
        this.AnalyticsModuleName = AnalyticsModuleName;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="DeleteAnalyticsModulesResponse", WrapperNamespace="http://www.onvif.org/ver20/analytics/wsdl", IsWrapped=true)]
public partial class DeleteAnalyticsModulesResponse
{
    
    public DeleteAnalyticsModulesResponse()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetAnalyticsModules", WrapperNamespace="http://www.onvif.org/ver20/analytics/wsdl", IsWrapped=true)]
public partial class GetAnalyticsModulesRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver20/analytics/wsdl", Order=0)]
    public string ConfigurationToken;
    
    public GetAnalyticsModulesRequest()
    {
    }
    
    public GetAnalyticsModulesRequest(string ConfigurationToken)
    {
        this.ConfigurationToken = ConfigurationToken;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetAnalyticsModulesResponse", WrapperNamespace="http://www.onvif.org/ver20/analytics/wsdl", IsWrapped=true)]
public partial class GetAnalyticsModulesResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver20/analytics/wsdl", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("AnalyticsModule")]
    public Config[] AnalyticsModule;
    
    public GetAnalyticsModulesResponse()
    {
    }
    
    public GetAnalyticsModulesResponse(Config[] AnalyticsModule)
    {
        this.AnalyticsModule = AnalyticsModule;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="ModifyAnalyticsModules", WrapperNamespace="http://www.onvif.org/ver20/analytics/wsdl", IsWrapped=true)]
public partial class ModifyAnalyticsModulesRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver20/analytics/wsdl", Order=0)]
    public string ConfigurationToken;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver20/analytics/wsdl", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute("AnalyticsModule")]
    public Config[] AnalyticsModule;
    
    public ModifyAnalyticsModulesRequest()
    {
    }
    
    public ModifyAnalyticsModulesRequest(string ConfigurationToken, Config[] AnalyticsModule)
    {
        this.ConfigurationToken = ConfigurationToken;
        this.AnalyticsModule = AnalyticsModule;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="ModifyAnalyticsModulesResponse", WrapperNamespace="http://www.onvif.org/ver20/analytics/wsdl", IsWrapped=true)]
public partial class ModifyAnalyticsModulesResponse
{
    
    public ModifyAnalyticsModulesResponse()
    {
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface AnalyticsEnginePortChannel : AnalyticsEnginePort, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class AnalyticsEnginePortClient : System.ServiceModel.ClientBase<AnalyticsEnginePort>, AnalyticsEnginePort
{
    
    public AnalyticsEnginePortClient()
    {
    }
    
    public AnalyticsEnginePortClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public AnalyticsEnginePortClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AnalyticsEnginePortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AnalyticsEnginePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public Capabilities GetServiceCapabilities()
    {
        return base.Channel.GetServiceCapabilities();
    }
    
    public SupportedAnalyticsModules GetSupportedAnalyticsModules(string ConfigurationToken)
    {
        return base.Channel.GetSupportedAnalyticsModules(ConfigurationToken);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    CreateAnalyticsModulesResponse AnalyticsEnginePort.CreateAnalyticsModules(CreateAnalyticsModulesRequest request)
    {
        return base.Channel.CreateAnalyticsModules(request);
    }
    
    public void CreateAnalyticsModules(string ConfigurationToken, Config[] AnalyticsModule)
    {
        CreateAnalyticsModulesRequest inValue = new CreateAnalyticsModulesRequest();
        inValue.ConfigurationToken = ConfigurationToken;
        inValue.AnalyticsModule = AnalyticsModule;
        CreateAnalyticsModulesResponse retVal = ((AnalyticsEnginePort)(this)).CreateAnalyticsModules(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    DeleteAnalyticsModulesResponse AnalyticsEnginePort.DeleteAnalyticsModules(DeleteAnalyticsModulesRequest request)
    {
        return base.Channel.DeleteAnalyticsModules(request);
    }
    
    public void DeleteAnalyticsModules(string ConfigurationToken, string[] AnalyticsModuleName)
    {
        DeleteAnalyticsModulesRequest inValue = new DeleteAnalyticsModulesRequest();
        inValue.ConfigurationToken = ConfigurationToken;
        inValue.AnalyticsModuleName = AnalyticsModuleName;
        DeleteAnalyticsModulesResponse retVal = ((AnalyticsEnginePort)(this)).DeleteAnalyticsModules(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetAnalyticsModulesResponse AnalyticsEnginePort.GetAnalyticsModules(GetAnalyticsModulesRequest request)
    {
        return base.Channel.GetAnalyticsModules(request);
    }
    
    public Config[] GetAnalyticsModules(string ConfigurationToken)
    {
        GetAnalyticsModulesRequest inValue = new GetAnalyticsModulesRequest();
        inValue.ConfigurationToken = ConfigurationToken;
        GetAnalyticsModulesResponse retVal = ((AnalyticsEnginePort)(this)).GetAnalyticsModules(inValue);
        return retVal.AnalyticsModule;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ModifyAnalyticsModulesResponse AnalyticsEnginePort.ModifyAnalyticsModules(ModifyAnalyticsModulesRequest request)
    {
        return base.Channel.ModifyAnalyticsModules(request);
    }
    
    public void ModifyAnalyticsModules(string ConfigurationToken, Config[] AnalyticsModule)
    {
        ModifyAnalyticsModulesRequest inValue = new ModifyAnalyticsModulesRequest();
        inValue.ConfigurationToken = ConfigurationToken;
        inValue.AnalyticsModule = AnalyticsModule;
        ModifyAnalyticsModulesResponse retVal = ((AnalyticsEnginePort)(this)).ModifyAnalyticsModules(inValue);
    }
}
}
