//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Onvif.Imaging
{

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.onvif.org/ver20/imaging/wsdl", ConfigurationName="ImagingPort")]
public interface ImagingPort
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver20/imaging/wsdl/GetServiceCapabilities", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="Capabilities")]
    Capabilities GetServiceCapabilities();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver20/imaging/wsdl/GetImagingSettings", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="ImagingSettings")]
    ImagingSettings20 GetImagingSettings(string VideoSourceToken);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver20/imaging/wsdl/SetImagingSettings", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    void SetImagingSettings(string VideoSourceToken, ImagingSettings20 ImagingSettings, bool ForcePersistence);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver20/imaging/wsdl/GetOptions", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="ImagingOptions")]
    ImagingOptions20 GetOptions(string VideoSourceToken);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver20/imaging/wsdl/Move", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    void Move(string VideoSourceToken, FocusMove Focus);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver20/imaging/wsdl/GetMoveOptions", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="MoveOptions")]
    MoveOptions20 GetMoveOptions(string VideoSourceToken);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver20/imaging/wsdl/FocusStop", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    void Stop(string VideoSourceToken);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver20/imaging/wsdl/GetStatus", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="Status")]
    ImagingStatus20 GetStatus(string VideoSourceToken);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver20/imaging/wsdl")]
public partial class Capabilities
{
    
    private System.Xml.XmlElement[] anyField;
    
    private bool imageStabilizationField;
    
    private bool imageStabilizationFieldSpecified;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool ImageStabilization
    {
        get
        {
            return this.imageStabilizationField;
        }
        set
        {
            this.imageStabilizationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ImageStabilizationSpecified
    {
        get
        {
            return this.imageStabilizationFieldSpecified;
        }
        set
        {
            this.imageStabilizationFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class ImagingStatus20Extension
{
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class FocusStatus20Extension
{
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class FocusStatus20
{
    
    private float positionField;
    
    private MoveStatus moveStatusField;
    
    private string errorField;
    
    private FocusStatus20Extension extensionField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public float Position
    {
        get
        {
            return this.positionField;
        }
        set
        {
            this.positionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public MoveStatus MoveStatus
    {
        get
        {
            return this.moveStatusField;
        }
        set
        {
            this.moveStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string Error
    {
        get
        {
            return this.errorField;
        }
        set
        {
            this.errorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public FocusStatus20Extension Extension
    {
        get
        {
            return this.extensionField;
        }
        set
        {
            this.extensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public enum MoveStatus
{
    
    /// <remarks/>
    IDLE,
    
    /// <remarks/>
    MOVING,
    
    /// <remarks/>
    UNKNOWN,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class ImagingStatus20
{
    
    private FocusStatus20 focusStatus20Field;
    
    private ImagingStatus20Extension extensionField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public FocusStatus20 FocusStatus20
    {
        get
        {
            return this.focusStatus20Field;
        }
        set
        {
            this.focusStatus20Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public ImagingStatus20Extension Extension
    {
        get
        {
            return this.extensionField;
        }
        set
        {
            this.extensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class ContinuousFocusOptions
{
    
    private FloatRange speedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public FloatRange Speed
    {
        get
        {
            return this.speedField;
        }
        set
        {
            this.speedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class FloatRange
{
    
    private float minField;
    
    private float maxField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public float Min
    {
        get
        {
            return this.minField;
        }
        set
        {
            this.minField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public float Max
    {
        get
        {
            return this.maxField;
        }
        set
        {
            this.maxField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class RelativeFocusOptions20
{
    
    private FloatRange distanceField;
    
    private FloatRange speedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public FloatRange Distance
    {
        get
        {
            return this.distanceField;
        }
        set
        {
            this.distanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public FloatRange Speed
    {
        get
        {
            return this.speedField;
        }
        set
        {
            this.speedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class AbsoluteFocusOptions
{
    
    private FloatRange positionField;
    
    private FloatRange speedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public FloatRange Position
    {
        get
        {
            return this.positionField;
        }
        set
        {
            this.positionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public FloatRange Speed
    {
        get
        {
            return this.speedField;
        }
        set
        {
            this.speedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class MoveOptions20
{
    
    private AbsoluteFocusOptions absoluteField;
    
    private RelativeFocusOptions20 relativeField;
    
    private ContinuousFocusOptions continuousField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public AbsoluteFocusOptions Absolute
    {
        get
        {
            return this.absoluteField;
        }
        set
        {
            this.absoluteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public RelativeFocusOptions20 Relative
    {
        get
        {
            return this.relativeField;
        }
        set
        {
            this.relativeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public ContinuousFocusOptions Continuous
    {
        get
        {
            return this.continuousField;
        }
        set
        {
            this.continuousField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class ContinuousFocus
{
    
    private float speedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public float Speed
    {
        get
        {
            return this.speedField;
        }
        set
        {
            this.speedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class RelativeFocus
{
    
    private float distanceField;
    
    private float speedField;
    
    private bool speedFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public float Distance
    {
        get
        {
            return this.distanceField;
        }
        set
        {
            this.distanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public float Speed
    {
        get
        {
            return this.speedField;
        }
        set
        {
            this.speedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SpeedSpecified
    {
        get
        {
            return this.speedFieldSpecified;
        }
        set
        {
            this.speedFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class AbsoluteFocus
{
    
    private float positionField;
    
    private float speedField;
    
    private bool speedFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public float Position
    {
        get
        {
            return this.positionField;
        }
        set
        {
            this.positionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public float Speed
    {
        get
        {
            return this.speedField;
        }
        set
        {
            this.speedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SpeedSpecified
    {
        get
        {
            return this.speedFieldSpecified;
        }
        set
        {
            this.speedFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class FocusMove
{
    
    private AbsoluteFocus absoluteField;
    
    private RelativeFocus relativeField;
    
    private ContinuousFocus continuousField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public AbsoluteFocus Absolute
    {
        get
        {
            return this.absoluteField;
        }
        set
        {
            this.absoluteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public RelativeFocus Relative
    {
        get
        {
            return this.relativeField;
        }
        set
        {
            this.relativeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public ContinuousFocus Continuous
    {
        get
        {
            return this.continuousField;
        }
        set
        {
            this.continuousField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class ImagingOptions20Extension2
{
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.onvif.org/ver10/schema", Order=0)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class ImageStabilizationOptionsExtension
{
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class ImageStabilizationOptions
{
    
    private ImageStabilizationMode[] modeField;
    
    private FloatRange levelField;
    
    private ImageStabilizationOptionsExtension extensionField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Mode", Order=0)]
    public ImageStabilizationMode[] Mode
    {
        get
        {
            return this.modeField;
        }
        set
        {
            this.modeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public FloatRange Level
    {
        get
        {
            return this.levelField;
        }
        set
        {
            this.levelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public ImageStabilizationOptionsExtension Extension
    {
        get
        {
            return this.extensionField;
        }
        set
        {
            this.extensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public enum ImageStabilizationMode
{
    
    /// <remarks/>
    OFF,
    
    /// <remarks/>
    ON,
    
    /// <remarks/>
    AUTO,
    
    /// <remarks/>
    Extended,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class ImagingOptions20Extension
{
    
    private System.Xml.XmlElement[] anyField;
    
    private ImageStabilizationOptions imageStabilizationField;
    
    private ImagingOptions20Extension2 extensionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public ImageStabilizationOptions ImageStabilization
    {
        get
        {
            return this.imageStabilizationField;
        }
        set
        {
            this.imageStabilizationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public ImagingOptions20Extension2 Extension
    {
        get
        {
            return this.extensionField;
        }
        set
        {
            this.extensionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class WhiteBalanceOptions20Extension
{
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class WhiteBalanceOptions20
{
    
    private WhiteBalanceMode[] modeField;
    
    private FloatRange yrGainField;
    
    private FloatRange ybGainField;
    
    private WhiteBalanceOptions20Extension extensionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Mode", Order=0)]
    public WhiteBalanceMode[] Mode
    {
        get
        {
            return this.modeField;
        }
        set
        {
            this.modeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public FloatRange YrGain
    {
        get
        {
            return this.yrGainField;
        }
        set
        {
            this.yrGainField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public FloatRange YbGain
    {
        get
        {
            return this.ybGainField;
        }
        set
        {
            this.ybGainField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public WhiteBalanceOptions20Extension Extension
    {
        get
        {
            return this.extensionField;
        }
        set
        {
            this.extensionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public enum WhiteBalanceMode
{
    
    /// <remarks/>
    AUTO,
    
    /// <remarks/>
    MANUAL,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class WideDynamicRangeOptions20
{
    
    private WideDynamicMode[] modeField;
    
    private FloatRange levelField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Mode", Order=0)]
    public WideDynamicMode[] Mode
    {
        get
        {
            return this.modeField;
        }
        set
        {
            this.modeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public FloatRange Level
    {
        get
        {
            return this.levelField;
        }
        set
        {
            this.levelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public enum WideDynamicMode
{
    
    /// <remarks/>
    OFF,
    
    /// <remarks/>
    ON,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class FocusOptions20Extension
{
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class FocusOptions20
{
    
    private AutoFocusMode[] autoFocusModesField;
    
    private FloatRange defaultSpeedField;
    
    private FloatRange nearLimitField;
    
    private FloatRange farLimitField;
    
    private FocusOptions20Extension extensionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AutoFocusModes", Order=0)]
    public AutoFocusMode[] AutoFocusModes
    {
        get
        {
            return this.autoFocusModesField;
        }
        set
        {
            this.autoFocusModesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public FloatRange DefaultSpeed
    {
        get
        {
            return this.defaultSpeedField;
        }
        set
        {
            this.defaultSpeedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public FloatRange NearLimit
    {
        get
        {
            return this.nearLimitField;
        }
        set
        {
            this.nearLimitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public FloatRange FarLimit
    {
        get
        {
            return this.farLimitField;
        }
        set
        {
            this.farLimitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public FocusOptions20Extension Extension
    {
        get
        {
            return this.extensionField;
        }
        set
        {
            this.extensionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public enum AutoFocusMode
{
    
    /// <remarks/>
    AUTO,
    
    /// <remarks/>
    MANUAL,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class ExposureOptions20
{
    
    private ExposureMode[] modeField;
    
    private ExposurePriority[] priorityField;
    
    private FloatRange minExposureTimeField;
    
    private FloatRange maxExposureTimeField;
    
    private FloatRange minGainField;
    
    private FloatRange maxGainField;
    
    private FloatRange minIrisField;
    
    private FloatRange maxIrisField;
    
    private FloatRange exposureTimeField;
    
    private FloatRange gainField;
    
    private FloatRange irisField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Mode", Order=0)]
    public ExposureMode[] Mode
    {
        get
        {
            return this.modeField;
        }
        set
        {
            this.modeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Priority", Order=1)]
    public ExposurePriority[] Priority
    {
        get
        {
            return this.priorityField;
        }
        set
        {
            this.priorityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public FloatRange MinExposureTime
    {
        get
        {
            return this.minExposureTimeField;
        }
        set
        {
            this.minExposureTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public FloatRange MaxExposureTime
    {
        get
        {
            return this.maxExposureTimeField;
        }
        set
        {
            this.maxExposureTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public FloatRange MinGain
    {
        get
        {
            return this.minGainField;
        }
        set
        {
            this.minGainField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public FloatRange MaxGain
    {
        get
        {
            return this.maxGainField;
        }
        set
        {
            this.maxGainField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public FloatRange MinIris
    {
        get
        {
            return this.minIrisField;
        }
        set
        {
            this.minIrisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public FloatRange MaxIris
    {
        get
        {
            return this.maxIrisField;
        }
        set
        {
            this.maxIrisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public FloatRange ExposureTime
    {
        get
        {
            return this.exposureTimeField;
        }
        set
        {
            this.exposureTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=9)]
    public FloatRange Gain
    {
        get
        {
            return this.gainField;
        }
        set
        {
            this.gainField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=10)]
    public FloatRange Iris
    {
        get
        {
            return this.irisField;
        }
        set
        {
            this.irisField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public enum ExposureMode
{
    
    /// <remarks/>
    AUTO,
    
    /// <remarks/>
    MANUAL,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public enum ExposurePriority
{
    
    /// <remarks/>
    LowNoise,
    
    /// <remarks/>
    FrameRate,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class BacklightCompensationOptions20
{
    
    private BacklightCompensationMode[] modeField;
    
    private FloatRange levelField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Mode", Order=0)]
    public BacklightCompensationMode[] Mode
    {
        get
        {
            return this.modeField;
        }
        set
        {
            this.modeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public FloatRange Level
    {
        get
        {
            return this.levelField;
        }
        set
        {
            this.levelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public enum BacklightCompensationMode
{
    
    /// <remarks/>
    OFF,
    
    /// <remarks/>
    ON,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class ImagingOptions20
{
    
    private BacklightCompensationOptions20 backlightCompensationField;
    
    private FloatRange brightnessField;
    
    private FloatRange colorSaturationField;
    
    private FloatRange contrastField;
    
    private ExposureOptions20 exposureField;
    
    private FocusOptions20 focusField;
    
    private IrCutFilterMode[] irCutFilterModesField;
    
    private FloatRange sharpnessField;
    
    private WideDynamicRangeOptions20 wideDynamicRangeField;
    
    private WhiteBalanceOptions20 whiteBalanceField;
    
    private ImagingOptions20Extension extensionField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public BacklightCompensationOptions20 BacklightCompensation
    {
        get
        {
            return this.backlightCompensationField;
        }
        set
        {
            this.backlightCompensationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public FloatRange Brightness
    {
        get
        {
            return this.brightnessField;
        }
        set
        {
            this.brightnessField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public FloatRange ColorSaturation
    {
        get
        {
            return this.colorSaturationField;
        }
        set
        {
            this.colorSaturationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public FloatRange Contrast
    {
        get
        {
            return this.contrastField;
        }
        set
        {
            this.contrastField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public ExposureOptions20 Exposure
    {
        get
        {
            return this.exposureField;
        }
        set
        {
            this.exposureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public FocusOptions20 Focus
    {
        get
        {
            return this.focusField;
        }
        set
        {
            this.focusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("IrCutFilterModes", Order=6)]
    public IrCutFilterMode[] IrCutFilterModes
    {
        get
        {
            return this.irCutFilterModesField;
        }
        set
        {
            this.irCutFilterModesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public FloatRange Sharpness
    {
        get
        {
            return this.sharpnessField;
        }
        set
        {
            this.sharpnessField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public WideDynamicRangeOptions20 WideDynamicRange
    {
        get
        {
            return this.wideDynamicRangeField;
        }
        set
        {
            this.wideDynamicRangeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=9)]
    public WhiteBalanceOptions20 WhiteBalance
    {
        get
        {
            return this.whiteBalanceField;
        }
        set
        {
            this.whiteBalanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=10)]
    public ImagingOptions20Extension Extension
    {
        get
        {
            return this.extensionField;
        }
        set
        {
            this.extensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public enum IrCutFilterMode
{
    
    /// <remarks/>
    ON,
    
    /// <remarks/>
    OFF,
    
    /// <remarks/>
    AUTO,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class ImagingSettingsExtension202
{
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.onvif.org/ver10/schema", Order=0)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class ImageStabilizationExtension
{
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class ImageStabilization
{
    
    private ImageStabilizationMode modeField;
    
    private float levelField;
    
    private bool levelFieldSpecified;
    
    private ImageStabilizationExtension extensionField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public ImageStabilizationMode Mode
    {
        get
        {
            return this.modeField;
        }
        set
        {
            this.modeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public float Level
    {
        get
        {
            return this.levelField;
        }
        set
        {
            this.levelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LevelSpecified
    {
        get
        {
            return this.levelFieldSpecified;
        }
        set
        {
            this.levelFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public ImageStabilizationExtension Extension
    {
        get
        {
            return this.extensionField;
        }
        set
        {
            this.extensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class ImagingSettingsExtension20
{
    
    private System.Xml.XmlElement[] anyField;
    
    private ImageStabilization imageStabilizationField;
    
    private ImagingSettingsExtension202 extensionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public ImageStabilization ImageStabilization
    {
        get
        {
            return this.imageStabilizationField;
        }
        set
        {
            this.imageStabilizationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public ImagingSettingsExtension202 Extension
    {
        get
        {
            return this.extensionField;
        }
        set
        {
            this.extensionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class WhiteBalance20Extension
{
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class WhiteBalance20
{
    
    private WhiteBalanceMode modeField;
    
    private float crGainField;
    
    private bool crGainFieldSpecified;
    
    private float cbGainField;
    
    private bool cbGainFieldSpecified;
    
    private WhiteBalance20Extension extensionField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public WhiteBalanceMode Mode
    {
        get
        {
            return this.modeField;
        }
        set
        {
            this.modeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public float CrGain
    {
        get
        {
            return this.crGainField;
        }
        set
        {
            this.crGainField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CrGainSpecified
    {
        get
        {
            return this.crGainFieldSpecified;
        }
        set
        {
            this.crGainFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public float CbGain
    {
        get
        {
            return this.cbGainField;
        }
        set
        {
            this.cbGainField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CbGainSpecified
    {
        get
        {
            return this.cbGainFieldSpecified;
        }
        set
        {
            this.cbGainFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public WhiteBalance20Extension Extension
    {
        get
        {
            return this.extensionField;
        }
        set
        {
            this.extensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class WideDynamicRange20
{
    
    private WideDynamicMode modeField;
    
    private float levelField;
    
    private bool levelFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public WideDynamicMode Mode
    {
        get
        {
            return this.modeField;
        }
        set
        {
            this.modeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public float Level
    {
        get
        {
            return this.levelField;
        }
        set
        {
            this.levelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LevelSpecified
    {
        get
        {
            return this.levelFieldSpecified;
        }
        set
        {
            this.levelFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class FocusConfiguration20Extension
{
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class FocusConfiguration20
{
    
    private AutoFocusMode autoFocusModeField;
    
    private float defaultSpeedField;
    
    private bool defaultSpeedFieldSpecified;
    
    private float nearLimitField;
    
    private bool nearLimitFieldSpecified;
    
    private float farLimitField;
    
    private bool farLimitFieldSpecified;
    
    private FocusConfiguration20Extension extensionField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public AutoFocusMode AutoFocusMode
    {
        get
        {
            return this.autoFocusModeField;
        }
        set
        {
            this.autoFocusModeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public float DefaultSpeed
    {
        get
        {
            return this.defaultSpeedField;
        }
        set
        {
            this.defaultSpeedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DefaultSpeedSpecified
    {
        get
        {
            return this.defaultSpeedFieldSpecified;
        }
        set
        {
            this.defaultSpeedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public float NearLimit
    {
        get
        {
            return this.nearLimitField;
        }
        set
        {
            this.nearLimitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NearLimitSpecified
    {
        get
        {
            return this.nearLimitFieldSpecified;
        }
        set
        {
            this.nearLimitFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public float FarLimit
    {
        get
        {
            return this.farLimitField;
        }
        set
        {
            this.farLimitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FarLimitSpecified
    {
        get
        {
            return this.farLimitFieldSpecified;
        }
        set
        {
            this.farLimitFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public FocusConfiguration20Extension Extension
    {
        get
        {
            return this.extensionField;
        }
        set
        {
            this.extensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class Rectangle
{
    
    private float bottomField;
    
    private bool bottomFieldSpecified;
    
    private float topField;
    
    private bool topFieldSpecified;
    
    private float rightField;
    
    private bool rightFieldSpecified;
    
    private float leftField;
    
    private bool leftFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float bottom
    {
        get
        {
            return this.bottomField;
        }
        set
        {
            this.bottomField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool bottomSpecified
    {
        get
        {
            return this.bottomFieldSpecified;
        }
        set
        {
            this.bottomFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float top
    {
        get
        {
            return this.topField;
        }
        set
        {
            this.topField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool topSpecified
    {
        get
        {
            return this.topFieldSpecified;
        }
        set
        {
            this.topFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float right
    {
        get
        {
            return this.rightField;
        }
        set
        {
            this.rightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool rightSpecified
    {
        get
        {
            return this.rightFieldSpecified;
        }
        set
        {
            this.rightFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float left
    {
        get
        {
            return this.leftField;
        }
        set
        {
            this.leftField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool leftSpecified
    {
        get
        {
            return this.leftFieldSpecified;
        }
        set
        {
            this.leftFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class Exposure20
{
    
    private ExposureMode modeField;
    
    private ExposurePriority priorityField;
    
    private bool priorityFieldSpecified;
    
    private Rectangle windowField;
    
    private float minExposureTimeField;
    
    private bool minExposureTimeFieldSpecified;
    
    private float maxExposureTimeField;
    
    private bool maxExposureTimeFieldSpecified;
    
    private float minGainField;
    
    private bool minGainFieldSpecified;
    
    private float maxGainField;
    
    private bool maxGainFieldSpecified;
    
    private float minIrisField;
    
    private bool minIrisFieldSpecified;
    
    private float maxIrisField;
    
    private bool maxIrisFieldSpecified;
    
    private float exposureTimeField;
    
    private bool exposureTimeFieldSpecified;
    
    private float gainField;
    
    private bool gainFieldSpecified;
    
    private float irisField;
    
    private bool irisFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public ExposureMode Mode
    {
        get
        {
            return this.modeField;
        }
        set
        {
            this.modeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public ExposurePriority Priority
    {
        get
        {
            return this.priorityField;
        }
        set
        {
            this.priorityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PrioritySpecified
    {
        get
        {
            return this.priorityFieldSpecified;
        }
        set
        {
            this.priorityFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public Rectangle Window
    {
        get
        {
            return this.windowField;
        }
        set
        {
            this.windowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public float MinExposureTime
    {
        get
        {
            return this.minExposureTimeField;
        }
        set
        {
            this.minExposureTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MinExposureTimeSpecified
    {
        get
        {
            return this.minExposureTimeFieldSpecified;
        }
        set
        {
            this.minExposureTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public float MaxExposureTime
    {
        get
        {
            return this.maxExposureTimeField;
        }
        set
        {
            this.maxExposureTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MaxExposureTimeSpecified
    {
        get
        {
            return this.maxExposureTimeFieldSpecified;
        }
        set
        {
            this.maxExposureTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public float MinGain
    {
        get
        {
            return this.minGainField;
        }
        set
        {
            this.minGainField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MinGainSpecified
    {
        get
        {
            return this.minGainFieldSpecified;
        }
        set
        {
            this.minGainFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public float MaxGain
    {
        get
        {
            return this.maxGainField;
        }
        set
        {
            this.maxGainField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MaxGainSpecified
    {
        get
        {
            return this.maxGainFieldSpecified;
        }
        set
        {
            this.maxGainFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public float MinIris
    {
        get
        {
            return this.minIrisField;
        }
        set
        {
            this.minIrisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MinIrisSpecified
    {
        get
        {
            return this.minIrisFieldSpecified;
        }
        set
        {
            this.minIrisFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public float MaxIris
    {
        get
        {
            return this.maxIrisField;
        }
        set
        {
            this.maxIrisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MaxIrisSpecified
    {
        get
        {
            return this.maxIrisFieldSpecified;
        }
        set
        {
            this.maxIrisFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=9)]
    public float ExposureTime
    {
        get
        {
            return this.exposureTimeField;
        }
        set
        {
            this.exposureTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ExposureTimeSpecified
    {
        get
        {
            return this.exposureTimeFieldSpecified;
        }
        set
        {
            this.exposureTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=10)]
    public float Gain
    {
        get
        {
            return this.gainField;
        }
        set
        {
            this.gainField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool GainSpecified
    {
        get
        {
            return this.gainFieldSpecified;
        }
        set
        {
            this.gainFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=11)]
    public float Iris
    {
        get
        {
            return this.irisField;
        }
        set
        {
            this.irisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IrisSpecified
    {
        get
        {
            return this.irisFieldSpecified;
        }
        set
        {
            this.irisFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class BacklightCompensation20
{
    
    private BacklightCompensationMode modeField;
    
    private float levelField;
    
    private bool levelFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public BacklightCompensationMode Mode
    {
        get
        {
            return this.modeField;
        }
        set
        {
            this.modeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public float Level
    {
        get
        {
            return this.levelField;
        }
        set
        {
            this.levelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LevelSpecified
    {
        get
        {
            return this.levelFieldSpecified;
        }
        set
        {
            this.levelFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class ImagingSettings20
{
    
    private BacklightCompensation20 backlightCompensationField;
    
    private float brightnessField;
    
    private bool brightnessFieldSpecified;
    
    private float colorSaturationField;
    
    private bool colorSaturationFieldSpecified;
    
    private float contrastField;
    
    private bool contrastFieldSpecified;
    
    private Exposure20 exposureField;
    
    private FocusConfiguration20 focusField;
    
    private IrCutFilterMode irCutFilterField;
    
    private bool irCutFilterFieldSpecified;
    
    private float sharpnessField;
    
    private bool sharpnessFieldSpecified;
    
    private WideDynamicRange20 wideDynamicRangeField;
    
    private WhiteBalance20 whiteBalanceField;
    
    private ImagingSettingsExtension20 extensionField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public BacklightCompensation20 BacklightCompensation
    {
        get
        {
            return this.backlightCompensationField;
        }
        set
        {
            this.backlightCompensationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public float Brightness
    {
        get
        {
            return this.brightnessField;
        }
        set
        {
            this.brightnessField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BrightnessSpecified
    {
        get
        {
            return this.brightnessFieldSpecified;
        }
        set
        {
            this.brightnessFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public float ColorSaturation
    {
        get
        {
            return this.colorSaturationField;
        }
        set
        {
            this.colorSaturationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ColorSaturationSpecified
    {
        get
        {
            return this.colorSaturationFieldSpecified;
        }
        set
        {
            this.colorSaturationFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public float Contrast
    {
        get
        {
            return this.contrastField;
        }
        set
        {
            this.contrastField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ContrastSpecified
    {
        get
        {
            return this.contrastFieldSpecified;
        }
        set
        {
            this.contrastFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public Exposure20 Exposure
    {
        get
        {
            return this.exposureField;
        }
        set
        {
            this.exposureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public FocusConfiguration20 Focus
    {
        get
        {
            return this.focusField;
        }
        set
        {
            this.focusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public IrCutFilterMode IrCutFilter
    {
        get
        {
            return this.irCutFilterField;
        }
        set
        {
            this.irCutFilterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IrCutFilterSpecified
    {
        get
        {
            return this.irCutFilterFieldSpecified;
        }
        set
        {
            this.irCutFilterFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public float Sharpness
    {
        get
        {
            return this.sharpnessField;
        }
        set
        {
            this.sharpnessField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SharpnessSpecified
    {
        get
        {
            return this.sharpnessFieldSpecified;
        }
        set
        {
            this.sharpnessFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public WideDynamicRange20 WideDynamicRange
    {
        get
        {
            return this.wideDynamicRangeField;
        }
        set
        {
            this.wideDynamicRangeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=9)]
    public WhiteBalance20 WhiteBalance
    {
        get
        {
            return this.whiteBalanceField;
        }
        set
        {
            this.whiteBalanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=10)]
    public ImagingSettingsExtension20 Extension
    {
        get
        {
            return this.extensionField;
        }
        set
        {
            this.extensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ImagingPortChannel : ImagingPort, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ImagingPortClient : System.ServiceModel.ClientBase<ImagingPort>, ImagingPort
{
    
    public ImagingPortClient()
    {
    }
    
    public ImagingPortClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ImagingPortClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ImagingPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ImagingPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public Capabilities GetServiceCapabilities()
    {
        return base.Channel.GetServiceCapabilities();
    }
    
    public ImagingSettings20 GetImagingSettings(string VideoSourceToken)
    {
        return base.Channel.GetImagingSettings(VideoSourceToken);
    }
    
    public void SetImagingSettings(string VideoSourceToken, ImagingSettings20 ImagingSettings, bool ForcePersistence)
    {
        base.Channel.SetImagingSettings(VideoSourceToken, ImagingSettings, ForcePersistence);
    }
    
    public ImagingOptions20 GetOptions(string VideoSourceToken)
    {
        return base.Channel.GetOptions(VideoSourceToken);
    }
    
    public void Move(string VideoSourceToken, FocusMove Focus)
    {
        base.Channel.Move(VideoSourceToken, Focus);
    }
    
    public MoveOptions20 GetMoveOptions(string VideoSourceToken)
    {
        return base.Channel.GetMoveOptions(VideoSourceToken);
    }
    
    public void Stop(string VideoSourceToken)
    {
        base.Channel.Stop(VideoSourceToken);
    }
    
    public ImagingStatus20 GetStatus(string VideoSourceToken)
    {
        return base.Channel.GetStatus(VideoSourceToken);
    }
}
}