//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Onvif.Recording
{

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.onvif.org/ver10/recording/wsdl", ConfigurationName="RecordingPort")]
public interface RecordingPort
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/recording/wsdl/GetServiceCapabilities", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="Capabilities")]
    Capabilities GetServiceCapabilities();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/recording/wsdl/CreateRecording", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="RecordingToken")]
    string CreateRecording(RecordingConfiguration RecordingConfiguration);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/recording/wsdl/DeleteRecording", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    void DeleteRecording(string RecordingToken);
    
    // CODEGEN: Parameter 'RecordingItem' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/recording/wsdl/GetRecordings", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="RecordingItem")]
    GetRecordingsResponse GetRecordings(GetRecordingsRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/recording/wsdl/SetRecordingConfiguration", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    void SetRecordingConfiguration(string RecordingToken, RecordingConfiguration RecordingConfiguration);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/recording/wsdl/GetRecordingConfiguration", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="RecordingConfiguration")]
    RecordingConfiguration GetRecordingConfiguration(string RecordingToken);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/recording/wsdl/GetRecordingOptions", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="Options")]
    RecordingOptions GetRecordingOptions(string RecordingToken);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/recording/wsdl/CreateTrack", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="TrackToken")]
    string CreateTrack(string RecordingToken, TrackConfiguration TrackConfiguration);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/recording/wsdl/DeleteTrack", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    void DeleteTrack(string RecordingToken, string TrackToken);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/recording/wsdl/GetTrackConfiguration", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="TrackConfiguration")]
    TrackConfiguration GetTrackConfiguration(string RecordingToken, string TrackToken);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/recording/wsdl/SetTrackConfiguration", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    void SetTrackConfiguration(string RecordingToken, string TrackToken, TrackConfiguration TrackConfiguration);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/recording/wsdl/CreateRecordingJob", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="JobToken")]
    string CreateRecordingJob(ref RecordingJobConfiguration JobConfiguration);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/recording/wsdl/DeleteRecordingJob", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    void DeleteRecordingJob(string JobToken);
    
    // CODEGEN: Parameter 'JobItem' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/recording/wsdl/GetRecordingJobs", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="JobItem")]
    GetRecordingJobsResponse GetRecordingJobs(GetRecordingJobsRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/recording/wsdl/SetRecordingJobConfiguration", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    void SetRecordingJobConfiguration(string JobToken, ref RecordingJobConfiguration JobConfiguration);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/recording/wsdl/GetRecordingJobConfiguration", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="JobConfiguration")]
    RecordingJobConfiguration GetRecordingJobConfiguration(string JobToken);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/recording/wsdl/SetRecordingJobMode", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    void SetRecordingJobMode(string JobToken, string Mode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/recording/wsdl/GetRecordingJobState", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="State")]
    RecordingJobStateInformation GetRecordingJobState(string JobToken);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/recording/wsdl")]
public partial class Capabilities
{
    
    private System.Xml.XmlElement[] anyField;
    
    private bool dynamicRecordingsField;
    
    private bool dynamicRecordingsFieldSpecified;
    
    private bool dynamicTracksField;
    
    private bool dynamicTracksFieldSpecified;
    
    private string[] encodingField;
    
    private float maxRateField;
    
    private bool maxRateFieldSpecified;
    
    private float maxTotalRateField;
    
    private bool maxTotalRateFieldSpecified;
    
    private float maxRecordingsField;
    
    private bool maxRecordingsFieldSpecified;
    
    private int maxRecordingJobsField;
    
    private bool maxRecordingJobsFieldSpecified;
    
    private bool optionsField;
    
    private bool optionsFieldSpecified;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool DynamicRecordings
    {
        get
        {
            return this.dynamicRecordingsField;
        }
        set
        {
            this.dynamicRecordingsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DynamicRecordingsSpecified
    {
        get
        {
            return this.dynamicRecordingsFieldSpecified;
        }
        set
        {
            this.dynamicRecordingsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool DynamicTracks
    {
        get
        {
            return this.dynamicTracksField;
        }
        set
        {
            this.dynamicTracksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DynamicTracksSpecified
    {
        get
        {
            return this.dynamicTracksFieldSpecified;
        }
        set
        {
            this.dynamicTracksFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string[] Encoding
    {
        get
        {
            return this.encodingField;
        }
        set
        {
            this.encodingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float MaxRate
    {
        get
        {
            return this.maxRateField;
        }
        set
        {
            this.maxRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MaxRateSpecified
    {
        get
        {
            return this.maxRateFieldSpecified;
        }
        set
        {
            this.maxRateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float MaxTotalRate
    {
        get
        {
            return this.maxTotalRateField;
        }
        set
        {
            this.maxTotalRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MaxTotalRateSpecified
    {
        get
        {
            return this.maxTotalRateFieldSpecified;
        }
        set
        {
            this.maxTotalRateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float MaxRecordings
    {
        get
        {
            return this.maxRecordingsField;
        }
        set
        {
            this.maxRecordingsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MaxRecordingsSpecified
    {
        get
        {
            return this.maxRecordingsFieldSpecified;
        }
        set
        {
            this.maxRecordingsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int MaxRecordingJobs
    {
        get
        {
            return this.maxRecordingJobsField;
        }
        set
        {
            this.maxRecordingJobsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MaxRecordingJobsSpecified
    {
        get
        {
            return this.maxRecordingJobsFieldSpecified;
        }
        set
        {
            this.maxRecordingJobsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool Options
    {
        get
        {
            return this.optionsField;
        }
        set
        {
            this.optionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OptionsSpecified
    {
        get
        {
            return this.optionsFieldSpecified;
        }
        set
        {
            this.optionsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class RecordingJobStateInformationExtension
{
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class RecordingJobStateTrack
{
    
    private string sourceTagField;
    
    private string destinationField;
    
    private string errorField;
    
    private string stateField;
    
    private System.Xml.XmlElement[] anyField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string SourceTag
    {
        get
        {
            return this.sourceTagField;
        }
        set
        {
            this.sourceTagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string Destination
    {
        get
        {
            return this.destinationField;
        }
        set
        {
            this.destinationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string Error
    {
        get
        {
            return this.errorField;
        }
        set
        {
            this.errorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string State
    {
        get
        {
            return this.stateField;
        }
        set
        {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=4)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class RecordingJobStateTracks
{
    
    private RecordingJobStateTrack[] trackField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Track", Order=0)]
    public RecordingJobStateTrack[] Track
    {
        get
        {
            return this.trackField;
        }
        set
        {
            this.trackField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class RecordingJobStateSource
{
    
    private SourceReference sourceTokenField;
    
    private string stateField;
    
    private RecordingJobStateTracks tracksField;
    
    private System.Xml.XmlElement[] anyField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public SourceReference SourceToken
    {
        get
        {
            return this.sourceTokenField;
        }
        set
        {
            this.sourceTokenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string State
    {
        get
        {
            return this.stateField;
        }
        set
        {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public RecordingJobStateTracks Tracks
    {
        get
        {
            return this.tracksField;
        }
        set
        {
            this.tracksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=3)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class SourceReference
{
    
    private string tokenField;
    
    private System.Xml.XmlElement[] anyField;
    
    private string typeField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    public SourceReference()
    {
        this.typeField = "http://www.onvif.org/ver10/schema/Receiver";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string Token
    {
        get
        {
            return this.tokenField;
        }
        set
        {
            this.tokenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    [System.ComponentModel.DefaultValueAttribute("http://www.onvif.org/ver10/schema/Receiver")]
    public string Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class RecordingJobStateInformation
{
    
    private string recordingTokenField;
    
    private string stateField;
    
    private RecordingJobStateSource[] sourcesField;
    
    private RecordingJobStateInformationExtension extensionField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string RecordingToken
    {
        get
        {
            return this.recordingTokenField;
        }
        set
        {
            this.recordingTokenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string State
    {
        get
        {
            return this.stateField;
        }
        set
        {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Sources", Order=2)]
    public RecordingJobStateSource[] Sources
    {
        get
        {
            return this.sourcesField;
        }
        set
        {
            this.sourcesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public RecordingJobStateInformationExtension Extension
    {
        get
        {
            return this.extensionField;
        }
        set
        {
            this.extensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class GetRecordingJobsResponseItem
{
    
    private string jobTokenField;
    
    private RecordingJobConfiguration jobConfigurationField;
    
    private System.Xml.XmlElement[] anyField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string JobToken
    {
        get
        {
            return this.jobTokenField;
        }
        set
        {
            this.jobTokenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public RecordingJobConfiguration JobConfiguration
    {
        get
        {
            return this.jobConfigurationField;
        }
        set
        {
            this.jobConfigurationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=2)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class RecordingJobConfiguration
{
    
    private string recordingTokenField;
    
    private string modeField;
    
    private int priorityField;
    
    private RecordingJobSource[] sourceField;
    
    private RecordingJobConfigurationExtension extensionField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string RecordingToken
    {
        get
        {
            return this.recordingTokenField;
        }
        set
        {
            this.recordingTokenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string Mode
    {
        get
        {
            return this.modeField;
        }
        set
        {
            this.modeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public int Priority
    {
        get
        {
            return this.priorityField;
        }
        set
        {
            this.priorityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Source", Order=3)]
    public RecordingJobSource[] Source
    {
        get
        {
            return this.sourceField;
        }
        set
        {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public RecordingJobConfigurationExtension Extension
    {
        get
        {
            return this.extensionField;
        }
        set
        {
            this.extensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class RecordingJobSource
{
    
    private SourceReference sourceTokenField;
    
    private bool autoCreateReceiverField;
    
    private bool autoCreateReceiverFieldSpecified;
    
    private RecordingJobTrack[] tracksField;
    
    private RecordingJobSourceExtension extensionField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public SourceReference SourceToken
    {
        get
        {
            return this.sourceTokenField;
        }
        set
        {
            this.sourceTokenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public bool AutoCreateReceiver
    {
        get
        {
            return this.autoCreateReceiverField;
        }
        set
        {
            this.autoCreateReceiverField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AutoCreateReceiverSpecified
    {
        get
        {
            return this.autoCreateReceiverFieldSpecified;
        }
        set
        {
            this.autoCreateReceiverFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Tracks", Order=2)]
    public RecordingJobTrack[] Tracks
    {
        get
        {
            return this.tracksField;
        }
        set
        {
            this.tracksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public RecordingJobSourceExtension Extension
    {
        get
        {
            return this.extensionField;
        }
        set
        {
            this.extensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class RecordingJobTrack
{
    
    private string sourceTagField;
    
    private string destinationField;
    
    private System.Xml.XmlElement[] anyField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string SourceTag
    {
        get
        {
            return this.sourceTagField;
        }
        set
        {
            this.sourceTagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string Destination
    {
        get
        {
            return this.destinationField;
        }
        set
        {
            this.destinationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=2)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class RecordingJobSourceExtension
{
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class RecordingJobConfigurationExtension
{
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/recording/wsdl")]
public partial class TrackOptions
{
    
    private int spareTotalField;
    
    private bool spareTotalFieldSpecified;
    
    private int spareVideoField;
    
    private bool spareVideoFieldSpecified;
    
    private int spareAudioField;
    
    private bool spareAudioFieldSpecified;
    
    private int spareMetadataField;
    
    private bool spareMetadataFieldSpecified;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int SpareTotal
    {
        get
        {
            return this.spareTotalField;
        }
        set
        {
            this.spareTotalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SpareTotalSpecified
    {
        get
        {
            return this.spareTotalFieldSpecified;
        }
        set
        {
            this.spareTotalFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int SpareVideo
    {
        get
        {
            return this.spareVideoField;
        }
        set
        {
            this.spareVideoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SpareVideoSpecified
    {
        get
        {
            return this.spareVideoFieldSpecified;
        }
        set
        {
            this.spareVideoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int SpareAudio
    {
        get
        {
            return this.spareAudioField;
        }
        set
        {
            this.spareAudioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SpareAudioSpecified
    {
        get
        {
            return this.spareAudioFieldSpecified;
        }
        set
        {
            this.spareAudioFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int SpareMetadata
    {
        get
        {
            return this.spareMetadataField;
        }
        set
        {
            this.spareMetadataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SpareMetadataSpecified
    {
        get
        {
            return this.spareMetadataFieldSpecified;
        }
        set
        {
            this.spareMetadataFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/recording/wsdl")]
public partial class JobOptions
{
    
    private int spareField;
    
    private bool spareFieldSpecified;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Spare
    {
        get
        {
            return this.spareField;
        }
        set
        {
            this.spareField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SpareSpecified
    {
        get
        {
            return this.spareFieldSpecified;
        }
        set
        {
            this.spareFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/recording/wsdl")]
public partial class RecordingOptions
{
    
    private JobOptions jobField;
    
    private TrackOptions trackField;
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public JobOptions Job
    {
        get
        {
            return this.jobField;
        }
        set
        {
            this.jobField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public TrackOptions Track
    {
        get
        {
            return this.trackField;
        }
        set
        {
            this.trackField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=2)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class TrackConfiguration
{
    
    private TrackType trackTypeField;
    
    private string descriptionField;
    
    private System.Xml.XmlElement[] anyField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public TrackType TrackType
    {
        get
        {
            return this.trackTypeField;
        }
        set
        {
            this.trackTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=2)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public enum TrackType
{
    
    /// <remarks/>
    Video,
    
    /// <remarks/>
    Audio,
    
    /// <remarks/>
    Metadata,
    
    /// <remarks/>
    Extended,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class GetTracksResponseItem
{
    
    private string trackTokenField;
    
    private TrackConfiguration configurationField;
    
    private System.Xml.XmlElement[] anyField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string TrackToken
    {
        get
        {
            return this.trackTokenField;
        }
        set
        {
            this.trackTokenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public TrackConfiguration Configuration
    {
        get
        {
            return this.configurationField;
        }
        set
        {
            this.configurationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=2)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class GetTracksResponseList
{
    
    private GetTracksResponseItem[] trackField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Track", Order=0)]
    public GetTracksResponseItem[] Track
    {
        get
        {
            return this.trackField;
        }
        set
        {
            this.trackField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class GetRecordingsResponseItem
{
    
    private string recordingTokenField;
    
    private RecordingConfiguration configurationField;
    
    private GetTracksResponseList tracksField;
    
    private System.Xml.XmlElement[] anyField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string RecordingToken
    {
        get
        {
            return this.recordingTokenField;
        }
        set
        {
            this.recordingTokenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public RecordingConfiguration Configuration
    {
        get
        {
            return this.configurationField;
        }
        set
        {
            this.configurationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public GetTracksResponseList Tracks
    {
        get
        {
            return this.tracksField;
        }
        set
        {
            this.tracksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=3)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class RecordingConfiguration
{
    
    private RecordingSourceInformation sourceField;
    
    private string contentField;
    
    private string maximumRetentionTimeField;
    
    private System.Xml.XmlElement[] anyField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public RecordingSourceInformation Source
    {
        get
        {
            return this.sourceField;
        }
        set
        {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string Content
    {
        get
        {
            return this.contentField;
        }
        set
        {
            this.contentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="duration", Order=2)]
    public string MaximumRetentionTime
    {
        get
        {
            return this.maximumRetentionTimeField;
        }
        set
        {
            this.maximumRetentionTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=3)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/schema")]
public partial class RecordingSourceInformation
{
    
    private string sourceIdField;
    
    private string nameField;
    
    private string locationField;
    
    private string descriptionField;
    
    private string addressField;
    
    private System.Xml.XmlElement[] anyField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=0)]
    public string SourceId
    {
        get
        {
            return this.sourceIdField;
        }
        set
        {
            this.sourceIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string Location
    {
        get
        {
            return this.locationField;
        }
        set
        {
            this.locationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=4)]
    public string Address
    {
        get
        {
            return this.addressField;
        }
        set
        {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=5)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetRecordings", WrapperNamespace="http://www.onvif.org/ver10/recording/wsdl", IsWrapped=true)]
public partial class GetRecordingsRequest
{
    
    public GetRecordingsRequest()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetRecordingsResponse", WrapperNamespace="http://www.onvif.org/ver10/recording/wsdl", IsWrapped=true)]
public partial class GetRecordingsResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/recording/wsdl", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("RecordingItem")]
    public GetRecordingsResponseItem[] RecordingItem;
    
    public GetRecordingsResponse()
    {
    }
    
    public GetRecordingsResponse(GetRecordingsResponseItem[] RecordingItem)
    {
        this.RecordingItem = RecordingItem;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetRecordingJobs", WrapperNamespace="http://www.onvif.org/ver10/recording/wsdl", IsWrapped=true)]
public partial class GetRecordingJobsRequest
{
    
    public GetRecordingJobsRequest()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetRecordingJobsResponse", WrapperNamespace="http://www.onvif.org/ver10/recording/wsdl", IsWrapped=true)]
public partial class GetRecordingJobsResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/recording/wsdl", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("JobItem")]
    public GetRecordingJobsResponseItem[] JobItem;
    
    public GetRecordingJobsResponse()
    {
    }
    
    public GetRecordingJobsResponse(GetRecordingJobsResponseItem[] JobItem)
    {
        this.JobItem = JobItem;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface RecordingPortChannel : RecordingPort, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class RecordingPortClient : System.ServiceModel.ClientBase<RecordingPort>, RecordingPort
{
    
    public RecordingPortClient()
    {
    }
    
    public RecordingPortClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public RecordingPortClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RecordingPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RecordingPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public Capabilities GetServiceCapabilities()
    {
        return base.Channel.GetServiceCapabilities();
    }
    
    public string CreateRecording(RecordingConfiguration RecordingConfiguration)
    {
        return base.Channel.CreateRecording(RecordingConfiguration);
    }
    
    public void DeleteRecording(string RecordingToken)
    {
        base.Channel.DeleteRecording(RecordingToken);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetRecordingsResponse RecordingPort.GetRecordings(GetRecordingsRequest request)
    {
        return base.Channel.GetRecordings(request);
    }
    
    public GetRecordingsResponseItem[] GetRecordings()
    {
        GetRecordingsRequest inValue = new GetRecordingsRequest();
        GetRecordingsResponse retVal = ((RecordingPort)(this)).GetRecordings(inValue);
        return retVal.RecordingItem;
    }
    
    public void SetRecordingConfiguration(string RecordingToken, RecordingConfiguration RecordingConfiguration)
    {
        base.Channel.SetRecordingConfiguration(RecordingToken, RecordingConfiguration);
    }
    
    public RecordingConfiguration GetRecordingConfiguration(string RecordingToken)
    {
        return base.Channel.GetRecordingConfiguration(RecordingToken);
    }
    
    public RecordingOptions GetRecordingOptions(string RecordingToken)
    {
        return base.Channel.GetRecordingOptions(RecordingToken);
    }
    
    public string CreateTrack(string RecordingToken, TrackConfiguration TrackConfiguration)
    {
        return base.Channel.CreateTrack(RecordingToken, TrackConfiguration);
    }
    
    public void DeleteTrack(string RecordingToken, string TrackToken)
    {
        base.Channel.DeleteTrack(RecordingToken, TrackToken);
    }
    
    public TrackConfiguration GetTrackConfiguration(string RecordingToken, string TrackToken)
    {
        return base.Channel.GetTrackConfiguration(RecordingToken, TrackToken);
    }
    
    public void SetTrackConfiguration(string RecordingToken, string TrackToken, TrackConfiguration TrackConfiguration)
    {
        base.Channel.SetTrackConfiguration(RecordingToken, TrackToken, TrackConfiguration);
    }
    
    public string CreateRecordingJob(ref RecordingJobConfiguration JobConfiguration)
    {
        return base.Channel.CreateRecordingJob(ref JobConfiguration);
    }
    
    public void DeleteRecordingJob(string JobToken)
    {
        base.Channel.DeleteRecordingJob(JobToken);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetRecordingJobsResponse RecordingPort.GetRecordingJobs(GetRecordingJobsRequest request)
    {
        return base.Channel.GetRecordingJobs(request);
    }
    
    public GetRecordingJobsResponseItem[] GetRecordingJobs()
    {
        GetRecordingJobsRequest inValue = new GetRecordingJobsRequest();
        GetRecordingJobsResponse retVal = ((RecordingPort)(this)).GetRecordingJobs(inValue);
        return retVal.JobItem;
    }
    
    public void SetRecordingJobConfiguration(string JobToken, ref RecordingJobConfiguration JobConfiguration)
    {
        base.Channel.SetRecordingJobConfiguration(JobToken, ref JobConfiguration);
    }
    
    public RecordingJobConfiguration GetRecordingJobConfiguration(string JobToken)
    {
        return base.Channel.GetRecordingJobConfiguration(JobToken);
    }
    
    public void SetRecordingJobMode(string JobToken, string Mode)
    {
        base.Channel.SetRecordingJobMode(JobToken, Mode);
    }
    
    public RecordingJobStateInformation GetRecordingJobState(string JobToken)
    {
        return base.Channel.GetRecordingJobState(JobToken);
    }
}
}